### ISSUE TITLE
The game does not finish

### ISSUE THREAD

**Issue by Pablohn26** [danprince/js13k-2022#2]
I have reached the end of the game but it does not finish. It keeps playing without new adversaries to defeat. 

![image](https://user-images.githubusercontent.com/1228418/194359653-a55ceb73-203c-4f11-af13-31a3be132697.png)

**Comment by danprince** [comment]
@Pablohn26 The game ends after level 10 when you beat the boss. There's some "cinematic" text that explains but I didn't have enough code left to add a proper ending.

If you want to fight more enemies after level 10, feel free to fork the repo and add your own levels here:
https://github.com/danprince/js13k-2022/blob/ecd86cb75b0634b8b964946fe90c39dda0e0e565/src/levels.ts#L124-L125
