### ISSUE TITLE
Licence ? (cool game btw!)

### ISSUE THREAD

**Issue by SeanScherer** [danprince/js13k-2022#3]
Hi Danprince,

I think you have a very cool game here :).  (Just got through the second time - first time I won due to a bug, I was killed but continued to play :P).

Anyway, I wanted to know what licence / if you are offering this under a certain licence? I think this is a game worth keeping around, maybe changing and adding to! (And a licence would be necessary to do that with clear terms).

Thanks for your time,

Sean

P.S. Did you ever happen to play the Stronghold "demo"?

**Comment by danprince** [comment]
Thanks Sean. Added the license in https://github.com/danprince/js13k-2022/commit/1986b980daacbaf64d5101f9ad47f20edd9170cb.

**Comment by SeanScherer** [comment]
Cool, thank you very much :) !
