### ISSUE TITLE
How great an interest in this game?

### ISSUE THREAD

**Issue by SeanScherer** [danprince/js13k-2022#7]
Hey, this is a question issue. (Posed here, since I have no other way of communicating).

I'd like to know whether/ how much you ( @danprince ) are interested in still doing with this game. Ie, is your view more along the lines of "This was a one-shot for the Game Jam, nice to fix bugs, but in general this is not something I see myself working on / playing with still" , or more towards "I like this game and reckon it could still go places - even if I might not have that much time to do that myself just now".

Makes an obvious difference for someone (ie me :P), interested in doing stuff with it, which is why I'm asking :) .

**Comment by danprince** [comment]
Hey @SeanScherer! Honestly, I don't see myself doing a huge amount with this version of the game. I'd be thrilled to see people forking and modding the game in its current state.

If I do revisit it (not impossible in the future when I have more time) it's pretty likely to be with a ground up rewrite, to expand on some of the ideas that I had to simplify right down to make the game fit within 13KB.

However, I am totally happy to accept PRs and help with debugging and adding improvements/features. Mostly just happy that people are still excited about it, even after the jam is long finished!

**Comment by SeanScherer** [comment]
Nice to hear :). 

I'm still getting used to working with Git, so it might still be a few days till I can show what I've been up to.

For everyone else active here in the issues (ie potentially interested?), @AshSimmonds , @nick-w-nick, I've created https://matrix.to/#/#norman-the-necromancer:matrix.org (the equivalent to a Discord server, but on Matrix). 

Just in case you're as die-hard about this game as I am and would like a better place to chat about it :)  (I made it 'cause I'd like to!).

**Comment by AshSimmonds** [comment]
What I love about this game as it stands is the simplicity to understand immediately and ramping of difficulty, and the jump-right-in once every few days to burn ten minutes with some fun.

Some of the less ephemeral things I'd like to introduce are scoreboards and "official" builds for speedrunners or whatever, stats over time, graveyards, etc.

Then there's player fun stuff like trophies for various playstyles, customisable Normans, AI "management sim" as in you tell your Norm how to play but don't do it yourself, etc.

From a dev standpoint it's a really cool base platform to build out a much more compelling game, and whilst the 13kb thing might disappear, perhaps it should be substituted for 13 minutes.

**Comment by SeanScherer** [comment]
Ok, we have pretty opposite views of where to go with it then :P. (Though I do appreciate those aspects as well, my thinking is more along the lines of "flesh it out into more of a 'real game' ").

The scoreboards, trophies and such are definitely something I'd be interested in as well, so maybe there's some room for sharing stuff :). 

Nick has already hopped onto the Matrix channel/server, so if you feel inclined, as said you're welcome to come as well 
(though I'm going to be on the road over the weekend, so won't be accessing it the next days [I run Element - my/the main Matrix client - via Desktop only] ).

Either way, see you round!
